"""user_id and message_id association for likes

Revision ID: 70b4d1f2fb19
Revises: 
Create Date: 2024-01-08 09:16:44.498979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b4d1f2fb19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_message_id_key', type_='unique')
        batch_op.create_unique_constraint('user_message_uc', ['user_id', 'message_id'])
        batch_op.drop_constraint('likes_message_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('likes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['message_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('likes_message_id_fkey', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('user_message_uc', type_='unique')
        batch_op.create_unique_constraint('likes_message_id_key', ['message_id'])

    # ### end Alembic commands ###
